### ISSUE TITLE
New option: Block ordering and indenting

### ISSUE THREAD

**Issue by vecmezoni** [csscomb/csscomb.js#199]
Sometimes you have this:
```css
.block {
    ...
}

.block__element { 
    ...
}

.other-block {
    ...
}
.block:hover { 
    ...
}

.block_modifier { 
    ...
}
```
and you want it to be this:
```css
.block {
    ...
}

    .block:hover { 
        ...
    }

    .block__element { 
        ...
    }

        .block__element_modifier { 
            ...
        }

.other-block {
    ...
}
```

Any suggestions?

**Comment by lkraav** [comment]
Is it possible to get block-indent to just skip closing-brace altogether? That would suit my purposes best. Looking around, it seemed like I'd have to re-implement getLastWhitespaceNode() from space-before-closing-brace.js inside block-indent.js.

**Comment by tonyganch** [comment]
Closing this issue as a wontfix. If anyone implements it as a plugin, please let me know so I post a link to our website.
