### ISSUE TITLE
Enhancement? Multiple group selectors on same line

### ISSUE THREAD

**Issue by marcovtwout** [csscomb/csscomb.js#202]
I would like to use the groups functionality to group selectors on the same line, instead of separated by newlines.

So instead of:

```
#div {
    position: absolute;
    top: 10px;
    left: 20px;

    display: block;

    width: 200px;
    height: 150px;
}
```

I would like:

```
#div {
    position: absolute; top: 10px; left: 20px;
    display: block;
    width: 200px; height: 150px;
}
```

Grouping like this gives a nice way of using more width and less lines, while maintaining readability. Is this already possible?
##

**Comment by jdalton** [comment]
Hi All!

I'm closing this because unless a PR is created it won't likely be addressed.
If you feel strongly about this request I encourage you to dig in and submit a PR 😸
