### ISSUE TITLE
SASS: Sort @extend separately from @include

### ISSUE THREAD

**Issue by christianmagill** [csscomb/csscomb.js#204]
This relates to issue #143, which I also believe is a good idea.

I feel that @extend should be sorted separately from @include as they are often used for different purposes.

When writing modular SASS, @extend is used to extend modules, and personally I'd like to see what modules a selector is extending first in my SASS, because it affects so much.

@include mixins are used more frequently as shorthand for multiple css rules.

Preferably, I'd like to be able to sort my @include mixins along with related css properties, as per issue #143.

Thanks

**Comment by ThiRaBrTNK** [comment]
I believe, that it's also a good idea to keep **@include** just right after **@extend**, cause this rules can be overridden too.

**Comment by ArmorDarks** [comment]
Guys, how are you going to override `@extend`?

It _adds_ class of selector, in which used `@extend`, to extended selector, not vice versa

Example:

``` sass
.extendMe {
  border: 0;
}

.class {
  @extend .extendMe;
  border: 1px solid #000;
}
```

result:

``` css
.extendMe,
.class {
  border: 0;
}

.class {
  border: 1px solid #000;
}
```

It's not important where exactly `@extend` has been placed — in the beginning of properties or in the end, and thus it doesn't affect overriding of properties in same selector.

It's more important in terms of code readability where it should be placed, I'd say.

**Comment by jeroenransijn** [comment]
Made this in my fork, only file changed is: https://github.com/csscomb/csscomb.js/blob/master/lib/options/sort-order.js

"$include mixinName" works for mixins with "@mixin mixinName", fallback is always to "$include" if the mixin name is not found.

**Comment by tonyganch** [comment]
Fixed in `dev`, send @hudochenkov some love for this feature :hearts:

**Comment by stowball** [comment]
Is there a timeframe for when this will get merged to master?

**Comment by hellobrian** [comment]
+1 is this going to be merged into `master`?

**Comment by Stram** [comment]
+1
