### ISSUE TITLE
SASS: & operator being sorted last

### ISSUE THREAD

**Issue by rlucha** [csscomb/csscomb.js#207]
given the example

```
.classname {
    outline: none;

    &:after {
        outline: 1px solid red;
    }

    @include element(item2) {
        outline: 1px solid blue;
    }
}
```

Outputs:

```
.classname {
    outline: none; outline: 1px solid red;

    @include element(item2) {
        outline: 1px solid blue;
    }

    &:after {
        outline: 1px solid red;
    }
}
```

Please add the option to include the new v3.3 operator "&" in the sorting order to prevent mixins overwrite properties
##

**Comment by paazmaya** [comment]
@tonyganch is there anything done yet related to this issue? I would like to help if needed

**Comment by jacobnijgh** [comment]
I'm having the same issues,  i'm not able to sort "&" operators or nested code blocks.
for example:

["..."],
["margin-top"]

Will put the margin-top above a nested code block instead of beneath, like so:

.....
margin-top: 30px;
li {
...
}

Any news or ideas yet on this?, thanks in advance!

**Comment by jdalton** [comment]
Hi All!

I'm closing this because unless a PR is created it won't likely be addressed.
If you feel strongly about this request I encourage you to dig in and submit a PR 😸
