### ISSUE TITLE
LESS mixin and extend breaks CSSComb

### ISSUE THREAD

**Issue by domellen** [csscomb/csscomb.js#222]
Till recently I had no problem using CSSComb on LESS files in Sublime Text 2. Now, with ST3, I get an error on my LESS files. I have found that the error appears when I use a mixin with a negative number, like so `.text-indent(-16px);` or an extend like so `&:extend(._pill-button);`

But I haven't checked all my files to see if something else bothers CSSComb.

The error message is:
/Users/ellen/Library/Application Support/Sublime Text 3/Packages/CSScomb JS/node_modules/csscomb/lib/csscomb.js:205
            throw new Error('Parsing error at ' + filename + ': ' + e.message)
                  ^
Error: Parsing error at undefined: Please check the validity of the CSS block starting from the line #15
    at Object.Comb.processString (/Users/ellen/Library/Application Support/Sublime Text 3/Packages/CSScomb JS/node_modules/csscomb/lib/csscomb.js:205:19)
    at Socket.<anonymous> (/Users/ellen/Library/Application Support/Sublime Text 3/Packages/CSScomb JS/csscomb.js:23:37)
    at Socket.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:919:16
    at process._tickCallback (node.js:419:13)

If I remove the offending line, or just the minus sign when that is the problem, it works fine

Ellen
##

**Comment by godban** [comment]
Actually it works partially, u can use:
```css
.foo:extend(.bar) {
    ...
}
```
but next one still get error:
```css
.foo {
    &:extend(.bar) {
        ...
    }
}

**Comment by MartinDoyleUK** [comment]
Just come across this issue, meaning I can't actually use CSSComb on several stylesheets in my project. Any update on a fix?

**Comment by AntoineBoulanger** [comment]
+1

**Comment by alexnewmannn** [comment]
Any updates on this?

**Comment by thephilipjones** [comment]
Lack of `&:extend()` support is making this pretty unusable for my project :disappointed:

**Comment by ulaharb** [comment]
Any updates with this issue?

**Comment by dsturm** [comment]
+1

**Comment by leopoldkristjansson** [comment]
+1

**Comment by Keysox** [comment]
+1

**Comment by leopoiroux** [comment]
+1

**Comment by adamskianthony** [comment]
never fixed?

**Comment by prosim** [comment]
+1

**Comment by Kevnz** [comment]
This is still an issue, any idea of what is going on, or is this not going to be sorted or even a point in the a direction to look at ways to fix it

**Comment by jdalton** [comment]
This is fixed in the latest csscomb release 🎉
