### ISSUE TITLE
New option: disable all potentially destructive options

### ISSUE THREAD

**Issue by kizu** [csscomb/csscomb.js#237]
There are already options in CSSComb.js that, when applied, couldn't be reverted.
- `remove-empty-rulesets` — would remove unfinished blocks of code, removing the selectors, which could contain some meaning to the code.
- `sort-order` — the original order could matter and couldn't be restored, and in case of preprocessors there could be cases when the order matters a lot.
- [`remove-comments`](https://github.com/csscomb/csscomb.js/issues/235) — comments are surely can't be placed back when stripped.
- Some of the options people could write if we would have Plugin API (#236).

Each option could have a flag telling if it is destructive, so it shouldn't be very hard to implement this.

On its own this option wouldn't make much sense (however, it would be still useful, as you could use one preset for some heavy combing and in the editor, where you'd like a safer environment), but if we would have Plugin API, there could be dozens of plugins and it would be nice to allow their authors to mark a plugin as a potentially destructive. Also, as you couldn't know the names of the options from the plugin (and the new options that could some day land in core CSSComb, as well as some third-party preset), having a one option that would disable the destructive options alltogether would be handy and useful.
##

**Comment by jdalton** [comment]
Hi @kizu!

I'm closing this because unless a PR is created it won't likely be addressed.
If you feel strongly about this request I encourage you to dig in and submit a PR 😸
