### ISSUE TITLE
Option to remove blank lines

### ISSUE THREAD

**Issue by danielbayley** [csscomb/csscomb.js#240]
Just what it says on the tin…
##

**Comment by discern** [comment]
Suggest splitting into two separate options:

1. Remove empty lines inside blocks
2. Number of newlines after closing brace

For example, I always add two newlines after a closing brace, and remove empties inside the braces.

<pre>
a {
	background: #fff
	
	color: #04c
}
b {
	font-weight: bold;
}
</pre>

would become:

<pre>
a {
	background: #fff;
	color: #04c;
}

b {
	font-weight: bold;
}
</pre>

Regardless, this is an awesome tool to have when inheriting a poorly written stylesheet. Thanks!

**Comment by mbrammer** [comment]
+1

**Comment by mkarkachov** [comment]
+1

**Comment by djouuuuh** [comment]
+1

**Comment by jdalton** [comment]
Hi All!

I'm closing this because unless a PR is created it won't likely be addressed.
If you feel strongly about this request I encourage you to dig in and submit a PR 😸
