### ISSUE TITLE
 csscomb: command not found

### ISSUE THREAD

**Issue by aart-rainey** [csscomb/csscomb.js#256]
I installed csscomb, but the command not found.
what i'm doing wrong?

$ npm install csscomb
csscomb@3.0.0-5 node_modules/csscomb
├── commander@2.0.0
├── vow@0.4.4
├── gonzales-pe@3.0.0-5
├── minimatch@0.2.12 (lru-cache@2.5.0, sigmund@1.0.0)
└── vow-fs@0.3.2 (vow-queue@0.3.1, node-uuid@1.4.0, glob@3.2.8)

i$ csscomb
-bash: csscomb: command not found

Thank you

**Comment by gitressa** [comment]
Thanks for clarifying @afknapping. I tried running the command from a directory after installing it there ("Local installation"), but it didn't work. Only after installing globally did it work ... From the documentation:

> Global installation (for use as a command-line tool):
> ```
> npm install csscomb -g
> ```
> Local installation (for use as a command-line tool within current directory):
> ```
> npm install csscomb
> ```
