### ISSUE TITLE
Formatting issues with the new version

### ISSUE THREAD

**Issue by lennymyr** [csscomb/csscomb.js#283]
CSScomb JS 3.0.0 comes with a bunch of great features but unfortunately I am having problems with it.

Under OS X the new version 3.0.0 installs to "~/Library/Application Support/Sublime Text 3/Packages/CSScomb" but needs to be installed to "CSScomb JS". This causes the plugin not finding the config files.

Also, the new version formats my .less file not as it used to, so that it can't compile. It puts opening braces in a new line and always uses 4 tabs.

Using my own configuration won't help, although I have tried to rename the "CSScomb" directory to "CSScomb JS" and tried to replace the " JS" from the Main.sublime-menu file.
##

**Comment by jdalton** [comment]
Closing as stale. Please ping back if you feel this still needs attention.
