### ISSUE TITLE
SCSS code with calculations fails

### ISSUE THREAD

**Issue by maxfenton** [csscomb/csscomb.js#284]
The Sublime Text plugin of CSScomb JS trips up on SCSS calculations.

example:

```
$gutter-width: 40px;

.wrapper {
    padding-right: #{ $gutter-width / 2 };
    padding-left: #{ $gutter-width / 2 };
}
```

![screen shot 2014-08-13 at 10 49 55 am](https://cloud.githubusercontent.com/assets/906502/3907157/31fa5a40-22f9-11e4-98b9-3e0ccb86c2a4.png)
![screen shot 2014-08-13 at 10 49 52 am](https://cloud.githubusercontent.com/assets/906502/3907158/31fbfa62-22f9-11e4-9464-79fdc161d5c0.png)
##

**Comment by maxfenton** [comment]
I wish I knew how to fix it! ¯\_(ツ)_/¯

**Comment by stephenbe** [comment]
+1

**Comment by rafaellyra** [comment]
Hey guys, someone can give me the config JSON and the expected result for this bug?  Tanks

**Comment by maxfenton** [comment]
@rafaellyra These are my settings in Sublime Text 3 (build 3083 for Mac) — https://gist.github.com/maxfenton/92459c528e623cf42a6d

**Comment by jdalton** [comment]
The example code block now parses in gpe so should work with the latest csscomb release 😸
