### ISSUE TITLE
editorconfig support

### ISSUE THREAD

**Issue by kizu** [csscomb/csscomb.js#29]
See http://editorconfig.org/ — it would be nice to make CSSComb somehow get some of the settings from the corresponding `.editorconfig` file.
##

**Comment by marcobiedermann** [comment]
:+1: Yeah, would be great

**Comment by jdalton** [comment]
Hi All!

I'm closing this because unless a PR is created it won't likely be addressed.
If you feel strongly about this request I encourage you to dig in and submit a PR 😸
