### ISSUE TITLE
Add option to set property:value case

### ISSUE THREAD

**Issue by markweston** [csscomb/csscomb.js#308]
I don't see any config options to add line breaks between all rulesets. Something like 'space-after-closing-brace'. Also there isn't a config option for setting the case of properties and values.

These sound like enhancements, but would be useful. I'm using grunt scss-lint and the configuration there is quite complex in comparison. 
##

**Comment by jdalton** [comment]
Hi All!

I'm closing this because unless a PR is created it won't likely be addressed.
If you feel strongly about this request I encourage you to dig in and submit a PR 😸
