### ISSUE TITLE
Problem with nested code + tag + colons in LESS

### ISSUE THREAD

**Issue by lhtdesignde** [csscomb/csscomb.js#311]
CssComb is continuing indenting when the following code occurs:

```
.list {
    overflow-y: auto;

    button::-moz-focus-inner {
      padding: 0;
    }
      .row {
        position: relative;
      }
        .row1 {
          overflow: hidden;
        }
}
```

As far as I was able to debug, this happens when there is a tag followed by a double colon (::). If you place the tag with a class it's fine. Was this issue address before? Is there some setting I can change to avoid this happening?
##

**Comment by tonyganch** [comment]
@lhtdesignde, do you still have trouble with this issue?

**Comment by lhtdesignde** [comment]
thanks. I don't have a setup with less at the moment. Should it be resolved?

**Comment by Gruntfuggly** [comment]
I'm having the same issue. Is there a work around?

**Comment by jdalton** [comment]
This seems to fixed in the latest csscomb release 🕺
