### ISSUE TITLE
Invalid CSS causes silent failures

### ISSUE THREAD

**Issue by iabw** [csscomb/csscomb.js#313]
Invalid CSS causes the file it's found in to not be processed without any notification.

This seems true regardless of the invalidity in question, but I specifically tested the `processFile` method and this invalid css `.someclass { #margin-right: -4px; }`. I lazily use this to comment out css for testing sometimes, as browsers don't render it (but don't barf either).

The return value of the function seems to be the same as a successful run - 

``` json
{
  "_value": undefined,
  "_status": 0,
  "_fulfilledCallbacks": [],
  "_rejectedCallbacks": [],
  "_progressCallbacks": []
}
```

but no modifications are made to the file.

I found this bug initially while using [grunt-csscomb](https://github.com/csscomb/grunt-csscomb). When processing multiple files, it would stop at the file with bad CSS, causing no files after the one that failed to be processed and claiming it had completed successfully. Note that [grunt-csscomb uses `processString` internally](https://github.com/csscomb/grunt-csscomb/blob/master/tasks/csscomb.js#L81), so it seems it's not a problem with processFile, but some core try block.

I would expect one of the following:
- a notification that the file failed to process with a reason why ( that does not cause grunt-csscomb to stop processing afterwards as it currently does )
- for the invalid rule to be removed and the file processed normally
- a full throw with a notification
##

**Comment by jdalton** [comment]
Hi All!

I'm closing this because unless a PR is created it won't likely be addressed.
If you feel strongly about this request I encourage you to dig in and submit a PR 😸
