### ISSUE TITLE
New option: Space between sort groups

### ISSUE THREAD

**Issue by Francisc** [csscomb/csscomb.js#314]
Hello,
Is it possible to remove the new-line separator between sort groups?
For example, because `display` and `vertical-align` are in different groups, they are separated by a new line. Boo!

Ah, and is there an easy way to move a property from one group to another without defining the entire sort array with the change? E.g. I want to have `vertical-align` under `display`.

Thanks.

**Comment by marcandrewb** [comment]
+1
I tried running what @JaredCowan provided but I got an error saying "Command Line too long"

**Comment by attenzione** [comment]
+1

**Comment by miszo** [comment]
+1

**Comment by tonyganch** [comment]
I’m closing this one as a wontfix. I’d like csscomb to have only essential options by default and this one does not seem critical enough to me to implement and support it.
If anyone implements it as a plugin, I'll be happy to put a link at README page and on website, so other people can use it.

**Comment by Francisc** [comment]
Haha.

**Comment by attenzione** [comment]
wrong move

**Comment by red2678** [comment]
"...so it can get some +1's from people who think the same way you do." So we gave you the +1's and you still closed it. Uummm. Well ok, that just happened. It would be  a very useful feature.

**Comment by tonyganch** [comment]
I don’t get why you’re so unhappy.
If this feature is so critical for your work, why have not you made a pr?
There has been 0 (zero) pr's for this issue since last year.

What I wanted to say by the "wontfix" label is — this feature won’t be part of this repo, yes, but you can still implement it as a plugin and share a link to your repo so everyone else can use it too.

**Comment by royriojas** [comment]
Is there such plugin yet? would be nice to know.

**Comment by rosswaycaster** [comment]
+1

**Comment by TommiHynynen** [comment]
+1

**Comment by najela** [comment]
+1
Pleaase wee need this option

**Comment by emage** [comment]
+1

**Comment by marcelmoreau** [comment]
+1

**Comment by itpastorn** [comment]
+1

**Comment by errazib** [comment]
+1

**Comment by Lakston** [comment]
+1

Using Atom (tried 3 different packages) on OSX.

I made a config with a 1D array but I'm still getting newlines between groups, example : 

`"sort-order": [
      [
        "position",
        "z-index",
        "top",
        "right",
        "bottom",
        "left"
        "display",
        "flex-direction",
        "flex-order",
        "flex-pack",
        "flex-align",
        "flex"
        "visibility",
        "float",
        "clear",
        "overflow",
        "overflow-x",
        "overflow-y",
        "-ms-overflow-x",
        "-ms-overflow-y",
        "clip",
        "zoom",

        "font",
        "font-family",
        "font-size",
        "line-height"
        "font-weight",
        "font-style",
        "font-variant",
        "font-size-adjust",
        "font-stretch",
        "font-effect",
        "font-emphasize",
        "font-emphasize-position",
        "font-emphasize-style",
        "font-smooth",
... rest of the options 
`

So I don't know how to remove those newlines since I applied what was recommended here and it is not working, I guess an option would be great. If I apply csscomb again I get 2 newlines, the 3 etc... this doesn't seem to be the normal behavior.

**Comment by Nathanw** [comment]
+1

**Comment by mrbinky3000** [comment]
+1

**Comment by pagegwood** [comment]
+1

**Comment by alexanderkram** [comment]
I don't want a space between my includes and properties. 
So i tried: `"sort-order": ["$include", "..."], "sort-order-fallback": "abc"`

Insert:
```
my-component {
 
  color: black;
  background-color: white;
   @include my-mixin();
}
```

Outcome:
```
my-component {
  background-color: white;
  color: black;
  @include my-mixin();
}
```

What i expected:
```
my-component {
  @include my-mixin();
  background-color: white;
  color: black;
}
```

I tried also: `"sort-order": ["$include"], "sort-order-fallback": "abc"`

Outcome:
```
my-component {
  @include my-mixin();

  background-color: white;
  color: black;
}
```

Please help to remove this ugly space between my includes and properties.

**Comment by andrewmartin** [comment]
+1

**Comment by andrewmartin** [comment]
For anyone interested, I did a quick hack and slash job and joined `yandex` rules into one big array. Took 30 seconds and it's getting me going for now... 

https://gist.github.com/andrewmartin/0dca43aaa050d5709bdec14a2b92697d

**Comment by eablokker** [comment]
+1

**Comment by dwilhel1** [comment]
+1

**Comment by typhoon2099** [comment]
+1
