### ISSUE TITLE
New option: Add ignore option for properties

### ISSUE THREAD

**Issue by seansheds** [csscomb/csscomb.js#323]
I'd like to recommend a new array option to add properties to ignore, including SCSS @variables, @include, and @extend.

Anything in the ignore option would be left in place.

We've had to disable csscomb in our projects because we need @extend's at the top and @include either left in place or at the bottom.  Since it treats extend's and include's as the same we weren't able to set it up the way we need.
##

**Comment by JoeShep** [comment]
Agreed. Our media queries are mixins and we need those to stay at the bottom, while other mixins would be at the top. Was hoping to use this on a new project, but this would be a showstopper.

**Comment by istro** [comment]
:heavy_plus_sign: :one:

I would also like a way to ignore comments.

**Comment by tonyganch** [comment]
I think #392 should fix this issue
