### ISSUE TITLE
"Configuration file path/to/file/.csscomb.json was not found" reported when JSON is simply not valid

### ISSUE THREAD

**Issue by augbog** [csscomb/csscomb.js#326]
Is there a way we can make it so that if you have invalid JSON, it throws a different error message? It's not a big deal, but thought I should make a mention of it because it is kind of misleading.

Ideally, it should only throw that error if it really does not exist there at all.
##

**Comment by istro** [comment]
+1.
For me, it was a missing comma between config options generated through the builder tool on the site and "sort-order" copied from a default config file.

**Comment by ixley** [comment]
+1 
New to JSON and tried adding comments. Error message through me off.
