### ISSUE TITLE
Corrupt sass code

### ISSUE THREAD

**Issue by kalashnikovisme** [csscomb/csscomb.js#332]
Does CssComb.js work with SASS?

I've tried to use it with SASS, and it's corrupted code. See screenshot of *git diff*.
![default](https://cloud.githubusercontent.com/assets/2001025/4887971/44a7ae88-6389-11e4-80c7-bfe8a54646c0.jpg)

Why?

**Comment by paazmaya** [comment]
I have similar experiences with same kind of input and output

**Comment by hudochenkov** [comment]
Before:

```sass
.block
  +media(lap)
    color: green

  +media(palm)
    color: red

  color: black

  +last
  +hide-text
```

After:

```sass
.block
color: black

  +media(lap)
    color: green

  +media(palm)
    color: red

  
  +last
  +hide-text
```

There are two spaces in line before `+last`.

Config:

```json
{ "sort-order": [

["color"], ["$include"]

]}
```

Run in command line: `node lib/cli.js include-specified-2.sass`

```
"version": "3.1.5" (current dev branch)
"csscomb-core": "3.0.0-4"
"gonzales-pe": "3.0.0-29"
```

**Comment by tonyganch** [comment]
@hudochenkov, green test for your issue, fixed in `dev`: https://github.com/csscomb/csscomb.js/blob/dev/test/options/sort-order-sass/test.js#L101

**Comment by tonyganch** [comment]
@kalashnikovisme, green test for your issue, fixed in `dev`: https://github.com/csscomb/csscomb.js/blob/dev/test/options/sort-order-sass/test.js#L108
