### ISSUE TITLE
New option: keep my indentation as is

### ISSUE THREAD

**Issue by kaless1n** [csscomb/csscomb.js#334]
I would love to have an option like 'keep-indent': true
To keep indentation in file as it is.

Example:

```
.block {
    somerules: somevals
    }
    .block-inner {
        somerules: somevals
        }
    .block-close {
        somerules: somevals
        }
```

And I don't want to change indentation at all according to code guide of company i work at.

**Comment by Marcel-Robitaille** [comment]
You might also want to remove `"space-after-selector-delimiter"`.

**Comment by robsonsobral** [comment]
It doesn't work. To remove the option make all indentation to be removed.
