### ISSUE TITLE
Large LESS File Crash

### ISSUE THREAD

**Issue by leggomuhgreggo** [csscomb/csscomb.js#336]
Hey I have a LESS file with like 3000 lines of code, and I tried running csscomb on it. Sublime just hung and it looked like a memory leak in the node instance, climbing steadily up from around 1.5GB, when I looked at my task manager.

Windows 8 i5 16GB
Node v 0.10.28
Sublime Text 3 
##

**Comment by jdalton** [comment]
Closing as stale. Please ping back if you feel this still needs attention.
