### ISSUE TITLE
Alphabetical ordering should order similar sass mixins from shortest to longest

### ISSUE THREAD

**Issue by kierzniak** [csscomb/csscomb.js#338]
Hi,
I have problem with this kind of scss:

```
.animation {
    @include animation(someanimation 1s);
    @include animation-play-state(paused);
}
```

Every time when I sort scss csscomb is swaping this two mixins. 

```
.animation {
    @include animation-play-state(paused);
    @include animation(someanimation 1s);
}
```

When I execute csscomb again mixin are swapped again:
```
.animation {
    @include animation(someanimation 1s);
    @include animation-play-state(paused);
}
```

CSS properties like 

```
.animation {
    animation: someanimation 1s;
    animation-play-state: paused;
}
```
are working fine.

node: v0.10.32
csscomb: 3.0.4 with default settings
command: ```csscomb _test.scss```

**Comment by dovyden** [comment]
maybe is it the same issue #366?

**Comment by kierzniak** [comment]
I checked this bug with new version of node and csscomb and now it is working properly.

node: v0.12.0
csscomb: 3.1.5 with default settings
