### ISSUE TITLE
Support for @at-root

### ISSUE THREAD

**Issue by QuentinFchx** [csscomb/csscomb.js#353]
in sass-indented mode [@at-root](https://github.com/sass/sass/issues/774) seems to break the parser.

``` sass
.btn
  @at-root a#{&}, &
  color: white
```
##

**Comment by aboutandre** [comment]
The issue persists. But if you're using the SASS 3.3 or higher you can ditch the @at-root in some cases:
`.list-item {
    @at-root #{&}__label {
    color: $foo-color;
    font-size: $foo-size;
    }
}
`
You can write just:
`.list-item {
    &__label {
    color: $foo-color;
    font-size: $foo-size;
    }
}
`
Check [parent selector suffixes](http://thesassway.com/news/sass-3-3-released#parent-selector-suffixes) for more info.

Hope this helps someone

**Comment by jdalton** [comment]
This no longer errors on the latest csscomb release 🎁
