### ISSUE TITLE
SASS Sort Order: @include specificity

### ISSUE THREAD

**Issue by jrweinb** [csscomb/csscomb.js#356]
I am requesting a feature where @includes can be given specificity when declaring sort-order. The reason is because some @includes belong at the top so that they can be overridden, while some belong at the bottom so they cannot be overridden (such as media query mixins). Example:

.csscomb.json

```
"sort-order":                      [
      [ "$variable" ],
      [ "$include" ]
      [
        "...",
      ],
      [ "$include @media" ]
  ]
```

In SCSS file:

```
.example-element {
   @include mixin1;
   float: left;
   padding-right: 10px;
   @include media($mobile-breakpoint) {
      padding-right: 20px;
  }
}
```

Sorting would preserve the ordering of the @include mixings

**Comment by joelzerner** [comment]
+1

**Comment by francoismassart** [comment]
+1

**Comment by kevinsperrine** [comment]
:+1:

**Comment by seavor** [comment]
+1

**Comment by ljcl** [comment]
Even better would be the ability to further sort based on the first variable of an include. e.g. Ensuring media-queries remain in the correct order:

```json
[ "$include @media($small)" ],
[ "$include @media($smaller)" ]
```

**Comment by denisborovikov** [comment]
Check this https://github.com/csscomb/csscomb.js/issues/143

**Comment by maxfenton** [comment]
+1

**Comment by jeroenransijn** [comment]
I don't know if supporting parameters is the right way to go. Although you can have a order by convention (small to large). I think to support what @ljcl mentions is only for a very small use case. The order of your media queries is important, I don't think CSSComb is really the tool to mess with developer intention, the same way you can't declare selector order.

**Comment by maxfenton** [comment]
I'd like to pipe in that I have a huge (for me) problem when using LESS or SASS with CSScomb if I extend another class.

For example: 

```
.h4 {
  font-size: bold;
  display: block;
}
.summary-list {
  li {
    .h4;
    display: inline-block;
    padding: 0 1em 0 0;
  }
}
```

If I run CSScomb, that gets reformatted to:

```
.h4 {
  font-size: bold;
  display: block;
}
.summary-list {
  li {
    display: inline-block;
    padding: 0 1em 0 0;

    .h4;
  }
}
```

So now the `block` overrides the `inline-block`.

I know that's not the best way for me to be writing my CSS, but sometimes on a site I don't have the option to add the `.h4` class to each list item and I don't want to duplicate the code from my styleguide.

To work around CSScomb, I wind up doing this:

```
```
.h4 {
  font-size: bold;
  display: block;
}
.summary-list {
  li {
    .h4;
  }
  li {
    display: inline-block;
    padding: 0 1em 0 0;
  }
}
```

Which works, but it would definitely be better for me if I could just tell CSScomb to boost things that start with a `.` to the top.

**Comment by Undistraction** [comment]
This is badly needed. There needs to be a way to order @extends before @includes, but allow specific @includes to exist inline without being reordered.

**Comment by tonyganch** [comment]
Fixed in `dev`, send @hudochenkov some love for this feature :hearts:

**Comment by maxfenton** [comment]
Thank you, @hudochenkov and @tonyganch! :+1:

**Comment by AxelBaron** [comment]
Hi,
So, it is possible to sort by includes like this ? 

`[ "$include mixin-one" ],
  "text-align",
  [ "$include mixin-two" ],
`

**Comment by jackeller** [comment]
I'm having issues sorting by mixin name as well.  It ignores any `["$include mixin-name"]` in my .csscomb config, but handles `$include` fine (and groups them all together).

**Comment by AxelBaron** [comment]
Yes me to. We can't choose where to put specific includes ? ( i don't want to group them together )

**Comment by aiboy** [comment]
@jackeller @AxelBaron plz create new issue with explanation as detailed as possible.
