### ISSUE TITLE
Horizontal Alignment and Comb on Save

### ISSUE THREAD

**Issue by Gliptal** [csscomb/csscomb.js#357]
Is there any chance a vertical alignment option can be implemented?

    h1 {
        font-size: 14px;
        background-color: red;
    }

to

    h1 {
        font-size       : 14px;
        background-color: red;
    }

Also, is there any way to automatically run the plugin whenever the .css file is saved?

**Comment by lrobeson** [comment]
@Gliptal Regarding your last question, if you're a Sublime Text user there's an existing request open for that: https://github.com/csscomb/sublime-csscomb/issues/53

**Comment by Gliptal** [comment]
Nice find, thanks.

**Comment by tonyganch** [comment]
@Gliptal, regarding your first question, no, there is no option to align properties.
