### ISSUE TITLE
doesn't support sass-function 'to-lower-case'

### ISSUE THREAD

**Issue by alfredbez** [csscomb/csscomb.js#360]
**test.scss**

``` scss
body {
  background: url(#{to-lower-case('Test.jpg')});
}
```

I get the following error when I run `csscomb test.scss`

```
stack:  test.scss
Please check the validity of the block starting from line #2

1 | body {
2*|   background: url(#{to-lower-case('Test.jpg')});
3 | }

Gonzales PE version: 3.0.0-10
CSScomb Core version: 2.0.4
```
##

**Comment by brunowego** [comment]
+1

**Comment by SamHH** [comment]
+1

I can also replicate this in the online tool (csscomb.com/online) with the following code:

    .test {
        width: calc(#{$site-width} + (#{$site-padding} * 2));
    }

**Comment by jdalton** [comment]
This no longer errors on the latest csscomb release 👍
