### ISSUE TITLE
Nothing Happens

### ISSUE THREAD

**Issue by kushalmahajan** [csscomb/csscomb.js#363]
Hi, I have nodejs installed and installed the plugin through package manager. Nothing happens when I run csscomb.

**Comment by tonyganch** [comment]
@kushalmahajan, is this issue still relevant?

**Comment by lisekyle** [comment]
This is also happening for me. Most recent version of node installed with Sublime Text 2.0.2 :(

**Comment by kushalmahajan** [comment]
@tonyganch  The comb works fine. Can't say what the exact issue was but it works now for me
