### ISSUE TITLE
scss not alphebatized

### ISSUE THREAD

**Issue by lfender6445** [csscomb/csscomb.js#364]
I found css comb through this [stackoverflow post](http://stackoverflow.com/questions/4566414/whats-the-best-tool-to-automatically-organize-or-alphabetize-your-css-propertie) 

my question, when using command line to run the comb through some scss files I noticed my selectors are not alphebetized - is this supported behavior of csscomb? 

also FWIW the webapp doesn't appear to support scss at all http://csscomb.com/online

**Comment by tonyganch** [comment]
Hello.
(1) This tool does not reorder selectors, there is no option for this.
(2) Yes, online tool works only for `css` syntax at the moment.
