### ISSUE TITLE
2to3 migration

### ISSUE THREAD

**Issue by a-x-** [csscomb/csscomb.js#365]
Hi!

Can you describe more explicitly how removed options should be replaced to new ones.

For example, i figured out, that:
`stick-brace`
decouple into two options
`space-before-opening-brace`
`space-after-opening-brace`

thank you!

**Comment by tonyganch** [comment]
I'm very sorry for delay with answer. Is the issue still relevant?

**Comment by a-x-** [comment]
— No care, this issue in my expectation list.

— Yep :-)

**Comment by a-x-** [comment]
And, i sure then this solution'll be useful for another people

**Comment by tonyganch** [comment]
1. `rule-indent` has been removed.
2. `colon-space` has been replaced with `space-before-colon` and `space-after-colon`.
3. `combinator-space` has been replaced with `space-before-combinator` and `space-after-combinator`.
4. `stick-brace` has been renamed to `space-before-opening-brace`.
5. New options have been added:
  - `space-after-opening-brace`,
  - `space-before-closing-brace`,
  - `space-before-selector-delimiter`,
  - `space-after-selector-delimiter`,
  - `sort-order-fallback`,
  - `space-between-declarations`,
  - `tab-size`

**Comment by a-x-** [comment]
Thank you, Tony! :cookie:
