### ISSUE TITLE
ampersand in variable name not working

### ISSUE THREAD

**Issue by alfredbez** [csscomb/csscomb.js#370]
**test.scss**

```
scss
@mixin something ($class)
{
    &#{$class}
    {
        color: red;
    }
}
.block
{
    $block: &;
    color: blue;
    @include something ('#{$block}--modifier')
}
```

I get the following error when I run `csscomb test.scss`

```
bash
stack:  test.scss
Please check the validity of the block starting from line #10

8 | .block
9 | {
10*|     $block: &;
11 |     color: blue;
12 |     @include something ('#{$block}--modifier')

Gonzales PE version: 3.0.0-10
CSScomb Core version: 2.0.4
```

See also: http://sass-compatibility.github.io/#ampersand_sassscript

SCSS compiles correctly using LibSass 3.2 or Sass 3.4. You can test it on http://sassmeister.com/

---

I'd be happy, if there where an option to ignore certain parts of a file (see #328).
##

**Comment by aTei** [comment]
Same problem. We actively use `&` in these 3 cases
```scss
.block {
 .cool-feature-detected & {
   // feature detection
 }

 &--element {
   // BEM naming
 }

 .layout-tree & {
   // layout
 }
}
```

**Comment by klojniewski** [comment]
Hello!

Any updates regarding this issue?

**Comment by jchouse** [comment]
The same problem with 
```
.parent {
    &#{&} { }
}
```
From there [csscomb-atom](https://github.com/jchouse/csscomb-atom/issues/27).

Did u have any idea why this happens.

**Comment by jdalton** [comment]
This does not error in the latest csscomb release 🎉
