### ISSUE TITLE
Feature request: ability to sort LESS extends to the top of a property list.

### ISSUE THREAD

**Issue by maxfenton** [csscomb/csscomb.js#372]
*Please tell me if this is a duplicate or already exists. I haven't found it in the issues, but I may have missed it.*

I'd like to pipe in that I have a huge (for me) problem when using LESS with CSScomb if I extend another class.

For example: 

```
.h4 {
  font-size: bold;
  display: block;
}
.summary-list {
  li {
    .h4;
    display: inline-block;
    padding: 0 1em 0 0;
  }
}
```

If I run CSScomb, that gets reformatted to:

```
.h4 {
  font-size: bold;
  display: block;
}
.summary-list {
  li {
    display: inline-block;
    padding: 0 1em 0 0;

    .h4;
  }
}
```

So now the `block` overrides the `inline-block`.

I know that's not the best way for me to be writing my CSS, but sometimes on a site I don't have the option to add the `.h4` class to each list item and I don't want to duplicate the code from my styleguide.

To work around CSScomb, I wind up doing this:

```
.h4 {
  font-size: bold;
  display: block;
}
.summary-list {
  li {
    .h4;
  }
  li {
    display: inline-block;
    padding: 0 1em 0 0;
  }
}
```

Which works, but it would definitely be better for me if I could just tell CSScomb to boost things that start with a `.` to the top.

*EDIT:* Same goes for SASS and `$`, of course.

**Comment by tonyganch** [comment]
You can specify this in config with `$include` like this:
```json
{
  "sort-order": [
    ["$include"], ["..."]
  ]
}
```
Which means: "put all includes to the top" and "sort everything else alphabetically"
