### ISSUE TITLE
Crashes on /deep/ selector

### ISSUE THREAD

**Issue by Thandriel** [csscomb/csscomb.js#374]
When /deep/ selector (from shadow DOM) is encountered csscomb crashes.

How to reproduce:

    html /deep/ span{
        display: block;
    }
Try to comb this.

**Comment by tonyganch** [comment]
@Thandriel, working on this one, thank you.
https://github.com/tonyganch/gonzales-pe/issues/64

**Comment by tonyganch** [comment]
Should be fixed in `3.1.0`
