### ISSUE TITLE
space-after-selector-delimiter using new line before children selector

### ISSUE THREAD

**Issue by micayael** [csscomb/csscomb.js#380]
Hi

I am using this configuration: 
```
"space-after-selector-delimiter": "\n"
```
but dosn't work when I use children selector.

With this example: 

```
.dropdown-menu {

    ...

    > li > a:hover, > li > a:focus {
            background: $naranja;
            color: $blanco;
        }
}
```

it dosn't break the line after the comma like this:

```
.dropdown-menu {

    ...

    > li > a:hover, 
    > li > a:focus {
            background: $naranja;
            color: $blanco;
        }
}
```

**Comment by tonyganch** [comment]
Can you please try following:
(1) update to `csscomb@3.1.3`;
(2) show me your full config?

**Comment by micayael** [comment]
I've installed the csscomb 3.1.3 globally but it seems the grunt-csscomb is still using the 3.0.0 version of csscomb instead of 3.1.3.

**Comment by micayael** [comment]
:+1:

**Comment by tonyganch** [comment]
@micayael, everything's fine now?

**Comment by micayael** [comment]
Yes. grunt-csscomb is updated now with csscomb 3.1.3 and fix the problem. Thanks.
