### ISSUE TITLE
What about --dry-run option?

### ISSUE THREAD

**Issue by a-x-** [csscomb/csscomb.js#383]
i want use csscomb in git pre-commit hook, and interrupt commit then immediately fix css

If exist something like dry-run option, i can compare combed file with source and detect
necessity of commit interrupting

Excuse my beginner's English and thank you

**Comment by a-x-** [comment]
Hmm, i found your cli documentation after seek
and found `--lint` option, as i see, it is what I need

**Comment by koistya** [comment]
@tonyganch it seems like `--lint` options doesn't work. E.g. when I run `csscomb src --verbose` it prints:

```
...
12 files processed
12 files fixed
spent: 185ms
```

But when I run `csscomb src --verbose --lint` it prints:

```
0 files processed
0 files fixed
spent: 101ms
```
