### ISSUE TITLE
Are you have cli documentation?

### ISSUE THREAD

**Issue by a-x-** [csscomb/csscomb.js#384]
Hi,

I try to find existing cli options and had defeat

Thank you

**Comment by a-x-** [comment]
Oh, i found: https://github.com/csscomb/csscomb.js/blob/master/doc/usage-cli.md
Here: http://csscomb.com/docs wrong Command Line link

**Comment by tonyganch** [comment]
Opened https://github.com/csscomb/www/issues/11, thank you
