### ISSUE TITLE
Cannot call method `is` of undefined

### ISSUE THREAD

**Issue by Priler** [csscomb/csscomb.js#387]
So.

1. In online version it gives this message "Dont be evil"

2. In SM plugin it give this error http://prntscr.com/78fo4j

3. In node.js plugin it gives this error http://prntscr.com/78folv

4. In gulp.js plugin it gives same error as in node.js plugin

What i do wrong?

**Comment by tonyganch** [comment]
Please provide the smallest piece of code which fails so i can test it.

**Comment by Priler** [comment]
/* http://meyerweb.com/eric/tools/css/reset/ 
   v2.0 | 20110126
   License: none (public domain)
*/

html, body, div, span, applet, object, iframe,
h1, h2, h3, h4, h5, h6, p, blockquote, pre,
a, abbr, acronym, address, big, cite, code,
del, dfn, em, img, ins, kbd, q, s, samp,
small, strike, strong, sub, sup, tt, var,
b, u, i, center,
dl, dt, dd, ol, ul, li,
fieldset, form, label, legend,
table, caption, tbody, tfoot, thead, tr, th, td,
article, aside, canvas, details, embed, 
figure, figcaption, footer, header, hgroup, 
menu, nav, output, ruby, section, summary,
time, mark, audio, video {
    margin: 0;
    padding: 0;
    border: 0;
    font-size: 100%;
    vertical-align: baseline;
}

**Comment by Priler** [comment]
Hey, i found a glitchi peace, give me a sec ...

**Comment by Priler** [comment]
Here you go http://pastebin.com/yFuCCxKC

**Comment by tonyganch** [comment]
Sigh... That's not «the smallest piece of code», you know.
Fixed in `csscomb@3.1.4`. You can check online: http://csscomb.com/online
