### ISSUE TITLE
Add/remove line break at EOF

### ISSUE THREAD

**Issue by paulca55** [csscomb/csscomb.js#390]
If I use  <b>"eof-newline": true</b> this adds the line break after the rule if I run csscomb on a single CSS rule. But if I select multiple rules then there is no line break in between each rule. Shouldn't it work like this? Thanks.

**Comment by tonyganch** [comment]
Do you expect something like #210?

**Comment by paulca55** [comment]
Yes that's what I meant. I'll give it a +1 thanks.
