### ISSUE TITLE
v3.1.5 makes decimal fractions unitless

### ISSUE THREAD

**Issue by 87carats** [csscomb/csscomb.js#394]
When both `leading-zero` and `unitless-zero` options are set `true`,

    $ csscomb --version
    3.1.5

    $ cat ./.csscomb.json
    {
      "leading-zero": true,
      "unitless-zero": true
    }

`csscomb` removes unit of decimal values less than 1.

    $ cat ./example.css
    .example {
      bottom: 0em;
      left:   0.5em;
      right:  1em;
      top:    1.5em;
    }

    $ csscomb --config ./.csscomb.json ./example.css

    $ cat ./example.css
    .example {
      bottom: 0;
      left:   0.5;
      right:  1em;
      top:    1.5em;
    }

Is this a bug?

**Comment by tonyganch** [comment]
Fixed in `csscomb@3.1.7`.
Thank you for report!
