### ISSUE TITLE
Add option for single line declarations

### ISSUE THREAD

**Issue by ixley** [csscomb/csscomb.js#395]
It would be great to have an option that would allow for single-line declarations, when there is a single property. I'm indifferent to whether it would also include support for multiple (comma delimited) selectors, or just a single one, but it is nice for reading when there aren't multiple properties.

By extension, this would conditionally adjust the behavior of `space-before-opening-brace` and `space-before-closing-brace`, and whatever other line wrapping behavior takes place.

I'm using this in conjunction with [scss-lint](https://github.com/brigade/scss-lint) and I like how the linter has certain logic for various options to allow for [single line rulesets](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#singlelineperproperty).

Single line properties as an exception:

```
.icon-chevron-up    { &:before { content: "\e030"; } }
.icon-chevron-down  { &:before { content: "\e031"; } }
.icon-chevron-left  { &:before { content: "\e032"; } }
.icon-chevron-right { &:before { content: "\e033"; } }
```

and standard formatting for multi-line declaration blocks:

```
p {
  margin: 0;
  padding: 0;
}
```
##

**Comment by danielbayley** [comment]
Definately +1 for this.

**Comment by rafaellyra** [comment]
:+1:

**Comment by sergiofontes** [comment]
👍

**Comment by jakobrosenberg** [comment]
👍

**Comment by arnolali** [comment]
+1

**Comment by beingmrkenny** [comment]
👍

**Comment by patrickording** [comment]
👍

**Comment by jdalton** [comment]
Hi All!

I'm closing this because unless a PR is created it won't likely be addressed.
If you feel strongly about this request I encourage you to dig in and submit a PR 😸
