### ISSUE TITLE
Don't wrap closing brace by default

### ISSUE THREAD

**Issue by ixley** [csscomb/csscomb.js#396]
The default closing brace formatting definitely caught my attention as strange – mostly because I'm used to formatting like this

```
selector {
  property: value;
}
```

instead of this

```
selector {
  property: value;
  }
```

I was glad to see that I can customize with `space-before-closing-brace` but it seems like there should also be the ability to ignore formatting and leave as is. (Maybe there's a way to do this I'm not familiar with? I tried passing 'false' with no luck...)

The main reason that setting `"space-before-closing-brace": "\n"` doesn't work for me across the board, is that I also want to be able to allow for [single line declarations (Issue #395)](https://github.com/csscomb/csscomb.js/issues/395), which then get reformatted like this

```
selector { property: value;
}
```

instead of

```
selector { property: value; }
```
##

**Comment by jdalton** [comment]
Hi @ixley !

I'm closing this because unless a PR is created it won't likely be addressed.
If you feel strongly about this request I encourage you to dig in and submit a PR 😸
