### ISSUE TITLE
lint doesn't work on csscomd#3.1.7

### ISSUE THREAD

**Issue by hyzhak** [csscomb/csscomb.js#402]
I'm trying to lint my less files and csscomd#3.1.7 doesn't get them. Because after `lintTree` it traps to https://github.com/csscomb/core/blob/build-dev/src/core.js#L268 and doesn't find any plugins that has `lint` method here https://github.com/csscomb/csscomb.js/blob/master/lib/options/. How can I get build of `csscomb` that has plugins with `lint` methods? As I see last dev branch has plugins with 'lint' method https://github.com/csscomb/csscomb.js/tree/dev/src/options. How can I get this build on npm?

**Comment by hyzhak** [comment]
just made some tests and found that it had broken between `3.0.4` and `3.1.0` version.

**Comment by tonyganch** [comment]
TL;DR: You cannot.

`csscomb-core#build-dev` is used only by `csscomb#dev` for, well, developing purpose. Those lint methods are work in progress and you should not really use them yet. They will be published with the next stable `4.0.0` release.

`csscomb#3.1.7` (the latest stable version, `master` branch) uses `csscomb-core#3.0.0-3` as a dependency, not `build-dev` branch, and it does not use lint methods in any way.

**Comment by hyzhak** [comment]
it doesn't mind. I've used those source code just to point where is problem. Lint of actual version (3.1.7) of this lib doesn't work. You can check it out. If you have published sources for it, I can point you where is problem. So for using lint I should downgrade to 3.0.x or waiting for new 4.x

**Comment by tonyganch** [comment]
Could you please update to `3.1.8` and tell me if the problem's still there?

**Comment by hyzhak** [comment]
@tonyganch yes, thanks! Now it works fine
