### ISSUE TITLE
request support: inherit configuration

### ISSUE THREAD

**Issue by septs** [csscomb/csscomb.js#408]
I expect and [zen](https://github.com/csscomb/csscomb.js/blob/master/config/zen.json) style just some details difference
But if custom configuration, then it will lose the advantage of the `sort-order` of `zen`
Therefore we want to support configuration inheritance

I want something like this:
```
{
    "inherit": "zen",
    "color-case": "upper"
}
```

THX

**Comment by tonyganch** [comment]
Here is the issue you should subscribe to: https://github.com/csscomb/csscomb.js/issues/299
