### ISSUE TITLE
CSSComb deletes CSS rules in .scss file

### ISSUE THREAD

**Issue by demrks** [csscomb/csscomb.js#420]
It seems as if CSScomb has some problems with "dynamic" class names. The following SCSS

```
.#{$ns-object}btn,
%#{$ns-object}btn {
    position: relative;
}
```

gets converted to 

```
.#{$ns-object}btn,
%#{$ns-object}btn
```

Although this SCSS (variable in class name) is valid the online tool outputs this error message

> Something went wrong.
> Please make sure that you're trying to comb a valid CSS (not Sass or Less).
> Or maybe you forgot a closing brace?
> 
> Here is an error message:
> 
> Please check the validity of the block starting from line #1
> 
> 1*| .#{$ns-object}btn,
> 2 | %#{$ns-object}btn {
> 3 |     position: relative;
> 
> Gonzales PE version: 3.0.0-28
> Syntax: css

**Comment by romamilkovic** [comment]
I confirm this bug. Any solutions?

**Comment by tonyganch** [comment]
Hi guys, the issue seems to be fixed with the latest release of csscomb 🐙
