### ISSUE TITLE
Add option to echo changes rather than modify file?

### ISSUE THREAD

**Issue by johnpgreen** [csscomb/csscomb.js#421]
Just starting to use csscomb after being a long-time user of Twitter's recess to ensure properties are in a consistent order. One thing I miss is the ability to have any changes the program wants to make be echo'd to stdout rather than made directly to the file itself. This is probably one part minor paranoia and one part wanting to know where I mis-ordered so I can try not to again in the future.

Is this an option that might be considered?
##

**Comment by mejarc** [comment]
I would enjoy this feature as well. I'm trying to introduce this to our front-end workflow, and the lack of feedback on the command line really spooks people.

**Comment by erikvold** [comment]
+1

**Comment by jdalton** [comment]
Hi All!

I'm closing this because unless a PR is created it won't likely be addressed.
If you feel strongly about this request I encourage you to dig in and submit a PR 😸
