### ISSUE TITLE
Multiple flexbox properties are missing

### ISSUE THREAD

**Issue by vitorgalvao** [csscomb/csscomb.js#423]
[Configurations](https://github.com/csscomb/csscomb.js/tree/master/config) are missing current flexbox properties, such as `flex`, `align-items`, `justify-content`, and others.

Was starting to add those, but stopped due to https://github.com/csscomb/csscomb.js/issues/422. Is there any preferred way to go about this?

**Comment by theotix** [comment]
+1 want !

**Comment by vitorgalvao** [comment]
Considering the lack of reply and repo activity, it’s likely this is abandoned.

I’ve since stopped using it anyway and even if I got an answer it’s unlikely I would work on it now.

Feel free to duplicate the issue if you want, @theotix.

Closing.
