### ISSUE TITLE
Media blocks in less are ignored by csscomb

### ISSUE THREAD

**Issue by seventhqueen** [csscomb/csscomb.js#425]
Hello,  really really nice plugin, congratulations on your work.

We are enable to make csscomb to process rules inside media queries like below example, it just ignores it
@media @tablet, @mobile {
//rules here
}

@tablet and @mobile are variables with the required media query for the device.

Maybe you know if renaming them into something else, making the processing with csscomb and then rename again to the initial name or any other workaround. 

Many thanks

**Comment by sodatea** [comment]
That's a bug in the old version of the gonzales-pe parser. Will fix in next release (or you can try the dev branch now).

**Comment by tonyganch** [comment]
Hey @seventhqueen, the issue has been fixed in the latest release of csscomb.

**Comment by seventhqueen** [comment]
Awesome to hear that. All the best
