### ISSUE TITLE
TypeError for IE7 hack style

### ISSUE THREAD

**Issue by markbrouch** [csscomb/csscomb.js#428]
I have a somewhat strange use case where I need to include the following style as an [IE7 hack](http://www.cssjunction.com/css/remove-dotted-border-in-ie7/):

```
.ie7 a {
  noFocusLine:expression(this.hideFocus=true)
}
```

However, this causes the following error when combing:

```
TypeError: block.is is not a function
```

Since I don't really care about this "property" being combed, it would be great if CSScomb could either do nothing for this type of property or if I could manually encapsulate this line in an ignore block, similar to how eslint works.
##

**Comment by jdalton** [comment]
This specific error is resolved in the latest csscomb release.
