### ISSUE TITLE
Csscomb + sass/scss/less variables alignment

### ISSUE THREAD

**Issue by klierik** [csscomb/csscomb.js#432]
Hello.

It will be good to add feature for alignment variables and values like:

```
$line-items-grid-border           : 0 none;
$line-items-grid-shadow           : none;
$line-items-grid-table-border-top : 0 none;
$validation-wrapper-border-top    : 0 none;
$create-receipt-grid-border       : 0 none;
$create-receipt-grid-shadow       : none;
```

And if the are at the beginning of file then add `!default` value (optional).

Maybe in future... :)

Thanks
##

**Comment by jongc** [comment]
Agreed. Additionally, variable values right aligned based on the longest variable name.

**Comment by johanneslamers** [comment]
please yes

**Comment by jdalton** [comment]
Hi All!

I'm closing this because unless a PR is created it won't likely be addressed.
If you feel strongly about this request I encourage you to dig in and submit a PR 😸
