### ISSUE TITLE
"Process out of memory" error for a big project

### ISSUE THREAD

**Issue by Awilum** [csscomb/csscomb.js#435]
Always I get this error

```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
Aborted (core dumped)
```

this is not helps me

```
node --max-old-space-size=6048 csscomb.js
```
##

**Comment by jdalton** [comment]
Hi @Awilum!

I'm closing as stale now since Node and V8 have changed a fair amount since 2015 and chances things perform a bit better now. Please feel free to ping back though with a test case if a problem persists.
