### ISSUE TITLE
Csscomb after stylus - sourcemap broken

### ISSUE THREAD

**Issue by romanlex** [csscomb/csscomb.js#449]
I want pretty my css code, and use csscomb after stylus. But sourcemap with csscomb is broken(
My config:
```javascript
gulp.task('style_stylus:build', function() {
    return gulp.src(path.src.style.stylus)
        .pipe(plumber())
        .pipe(sourcemaps.init())
        .pipe(stylus({
            use: [ autoprefixer_stylus({ browsers : ["last 4 version", 'ie 8', 'ie 9', '> 5%'] })],
        }))
        //.pipe(csscomb()) 
        .pipe(gulp.dest(path.build.css))
        .pipe(nano({zindex: false, mergeRules: false, discardComments: {removeAll: true}}))
        .pipe(rename({suffix: '.min'}))
        .pipe(sourcemaps.write('./', {
            includeContent: false,
            relativeToSourcePath: '/build',
            sourceRoot: '/src/style/stylus'
        }))
        .pipe(gulp.dest(path.build.css))
        .pipe(plumber.stop())
        .pipe(reload({stream: true, match: '**/*.css'}))
        .pipe(notify({ title: '[Gulp] CSS Build', message: 'Stylus task complete', onLast: true, wait: false }));
});
```
Without csscomb(work properly):
![screenshot_2016-02-02_00-14-06](https://cloud.githubusercontent.com/assets/3369304/12731430/01c0c0b2-c942-11e5-952a-733708d631e9.png)
With csscomb:
![screenshot_2016-02-02_00-14-36](https://cloud.githubusercontent.com/assets/3369304/12731442/0ca0426e-c942-11e5-82d1-d25c369ef1df.png)

**Comment by sodatea** [comment]
This is because gulp-csscomb does not support sourcemaps yet.

According to gulp-sourcemaps, [adding sourcemap support](https://github.com/floridoo/gulp-sourcemaps#plugin-developers-only-how-to-add-source-map-support-to-plugins) is quite trivial.

Since that plugin is not maintained by the csscomb team, I'd suggest you to fork and submit a PR for it by yourself.
