### ISSUE TITLE
CSSComb online tool

### ISSUE THREAD

**Issue by macik** [csscomb/csscomb.js#453]
I think for better UX it would be helpful if «try online» tool have some sample code already entered in text area, so user can try just by pressing «Comb It» button and not get long find any sample on own hard drive to try.

Drag'n'drop is also a good way to extend UX.

Any way thanks for a good tool.
##

**Comment by jdalton** [comment]
Hi @macik!

I'm closing this because unless a PR is created it won't likely be addressed.
If you feel strongly about this request I encourage you to dig in and submit a PR 😸
