### ISSUE TITLE
How do I skip a SCSS line that can't be parsed?

### ISSUE THREAD

**Issue by dnl** [csscomb/csscomb.js#465]
CSS comb doesn't know what to do with this line: 
```
width: calc(100% + #{$panel-padding * 2});
```

I am happy for it to just ignore it, but there doesn't appear to be a way to tell CSS comb to ignore a line.

**Comment by tonyganch** [comment]
Hey @dnl! The issue you're mentioning has been fixed in `csscomb@4.0.0-alpha`.
As for you question about ignoring a specific line, there is currently no way to do that and it's not planned for near future.
