### ISSUE TITLE
Обработка *.less файлов

### ISSUE THREAD

**Issue by bashkos** [csscomb/csscomb.js#466]
Здравствуйте! У нас возникло пара проблем при обработке утилитой *.less файлов:

- вызывает ошибку следующая сточка `.mxn-transition(background @duration-s, height (@desc-fade-duration * 2););`. Мы компилируем файлы с включенной опцией `--strict-math=on`, а потому вынуждены использовать скобки для выделения математических операций, но именно они и являются причиной ошибки в данном случае;
- правило `a:hover` превращается в `a: hover`. Возможно это из-за настроек, связанных с пробелами у двоеточия.

**Comment by bashkos** [comment]
Первая проблема связана с беблиотекой `gonzales-pe`. Версия, используемая в `csscomb` (3.0.0-28) имеет трудности с анализом скобок, даже если они валидны. В последней на текущий момент версии (3.3.1) это исправлено.

**Comment by tonyganch** [comment]
Привет! У `csscomb@4.0.0-alpha` более свежая версия парсера, и всё должно быть окей с обеими проблемами.
