### ISSUE TITLE
Allow inline comments for ignoring code parts

### ISSUE THREAD

**Issue by rugk** [csscomb/csscomb.js#471]
The issue is generally described in https://github.com/eslint/eslint/issues/6560. The short version is: I use Jekyll/Liquid, which has a special syntax, but this syntax is considered as a syntax error by csscomb.

So e.g. take this example:

``` sass
$site-header-height: {{ site.headersize }}px;
```

I get a syntax error and csscomb does not lint the file.

It would be nice if you could...
- add some way to ignore these syntax errors, e.g. with inline comments:

``` sass
// csscomb:ignore //
$site-header-height: {{ site.headersize }}px;
// csscomb:ignore-end //
```
## How other parsers/linters/... are doing it
- https://github.com/sasstools/sass-lint/issues/768
- https://github.com/jshint/jshint/issues/2969
##

**Comment by jdalton** [comment]
Hi @rugk!

I'm closing this because unless a PR is created it won't likely be addressed.
If you feel strongly about this request I encourage you to dig in and submit a PR 😸
