### ISSUE TITLE
Error on scss interpolation

### ISSUE THREAD

**Issue by Ebulavina** [csscomb/csscomb.js#474]
Parsing error: Please check the validity of the block starting from line #5

3 | .gallery {
4 |   left: -$gutter;
5*|   width: calc(100% + #{$gutter * 2});
6 |   height: 100%;
7 |   margin: 30px 0;

Gonzales PE version: 3.0.0-28
Syntax: scss

**Comment by mkhazov** [comment]
The problem is csscomb.js v3.1.7 uses the old version of gonzales-pe

**Comment by tonyganch** [comment]
Fixed in dev, will be released as version 4.0

**Comment by brianmilner** [comment]
Any updates on when this will be released offically? I could use the fix for this. Thanks
