### ISSUE TITLE
`--lint` always exits with 0 status

### ISSUE THREAD

**Issue by timoxley** [csscomb/csscomb.js#478]
According to the csscomb 3.1.7 docs:

```
    -l, --lint           in case some fixes needed returns an error
```

#### 3.1.7 & 4.0.0

```bash
> echo '*{color:red}' > style.css
> csscomb --lint style.css
> echo $?
0
```

**Comment by timoxley** [comment]
Note this makes it impractical to use `csscomb` in any kind of automated environment

**Comment by tonyganch** [comment]
Should be fixed in `dev` with one important note: linter mode will be default in v4.0.
That means that `csscomb file.css` will run linter and `csscomb --fix file.css` will modify the file.

**Comment by timoxley** [comment]
Perfect.
