### ISSUE TITLE
SCSS code sample generates a Gonzales PE error

### ISSUE THREAD

**Issue by prettydiff** [csscomb/csscomb.js#481]
https://github.com/Glavin001/atom-beautify/issues/1129
##

**Comment by tomagladiator** [comment]
I find this too, csscomb doesn't like [interpolation](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#interpolation_):
```
.bg-#{$color} {
    ...
}
```

**Comment by sergey-kozlov** [comment]
Please check the validity of the block starting from line #13

11 |     &__content {
12 |         @include fading-show('hidden');
13*|         margin: $gutter-half #{-$gutter-half} 0;
14 |         padding: $gutter-half;
15 |         background: $contentColor;

Gonzales PE version: 3.0.0-28
Syntax: scss
CSScomb Core version: 3.0.0-3

This is CSScomb or Gonzales bug?

**Comment by thejamespower** [comment]
CSSComb bug caused by an outdated version of Gonzales. See [here](https://github.com/tonyganch/gonzales-pe/issues/243).

**Comment by jdalton** [comment]
This should be fixed with the latest release 🎉
