### ISSUE TITLE
csscomb package in node.js obsolete ?

### ISSUE THREAD

**Issue by tomagladiator** [csscomb/csscomb.js#482]
Hi,

I'm not sure about that, but I think the package in[ nodejs here](https://www.npmjs.com/package/csscomb) is obsolete (1 year).

Because, we don't find the new option:  lines-between-rulesets.js.
`npm publish`

Thanks
##

**Comment by mrmlnc** [comment]
Try `npm install 4.0.0-alpha`.

**Comment by leggomuhgreggo** [comment]
Hmm, this didn't work for me. I noticed this in the install tree `csscomb-core@3.0.6`, and it occurred to me that might be the older version.

**Comment by vincentaudebert** [comment]
@mrmlnc even on 4.0.0-alpha it doesn't seem to work for some reason?
I added `"lines-between-rulesets": 1,` to my config file and it doesn't change files like
```
.one-tenth {
    width: 10%;
}
.one-quarter {
    width: 25%;
}
.one-fifth {
    width: 20%;
}
```

**Comment by CaitlinWeb** [comment]
I can confirm there's something wrong with the npm package. Here is what it looks like after updating to the alpha version. 

![csscomb version](https://cloud.githubusercontent.com/assets/6975769/19564945/32b480e8-96b3-11e6-8829-695adc487d24.PNG)

I also tried to update csscomb-core but it made no difference.

**Comment by jdalton** [comment]
Hi All!

[v4.3.0](https://www.npmjs.com/package/csscomb/v/4.3.0) was published a week or so ago. 👍
