### ISSUE TITLE
SCSS "$include mq" not working

### ISSUE THREAD

**Issue by herkulano** [csscomb/csscomb.js#483]
Sort order is not working properly for $include:
```json
"sort-order": [
      [ "$variable" ],
      [ "$include" ],
      [ "..." ],
      [ "$include mq" ]
    ]
```

Should output to:
```scss
.class {
  @include some-function();

  // styles...

  @include mq(mobile, tablet) {
    // styles...
  }
}
```

Instead outputs to:
```scss
.class {
  @include some-function();
  @include mq(mobile, tablet) {
    // styles...
  }

  // styles...
}
```

![d93379fc-6575-11e6-8e30-eeb255ed6d38-1](https://cloud.githubusercontent.com/assets/125300/17802415/d2d39316-65f8-11e6-930a-39eae4cea50d.gif)

https://github.com/mrmlnc/vscode-csscomb/issues/13

**Comment by symmetriq** [comment]
Same problem here. The mixins I've specified should be sorted *after* other properties are just moving to the top.

**Comment by herkulano** [comment]
This has been fixed in `v4.0.0-alpha` in current `develop` branch.

**Comment by alexranc** [comment]
@herkulano 

I also noticed this issue. $include-media is also not working properly.

How can I go about implementing v4.0.0-alpha if I installed csscomb via npm? Would love to be on the latest version.

Thank you!

**Comment by herkulano** [comment]
@alexranc set the version you want to install
`npm i -g csscomb@4.0.0-alpha`
