### ISSUE TITLE
CLI linting doesn't work

### ISSUE THREAD

**Issue by ascariandrea** [csscomb/csscomb.js#487]
Hi guys, I got this issue using the `-l` option in `3.1.7` release.

When I lint my files I get this output:

```
$ csscomb -lv src/app

0 files processed
0 files fixed
spent: 1205.418ms
```

while I format them I get the following one

```
$ csscomb -v src/app

95 files processed
21 files fixed
spent: 3685.675ms
```

As you can see the `processed` count is not consistent, and no error is returned even if there are 21 files that need to be fixed.

Let me know if you're already aware of this, thanks.
##

**Comment by shuhrat** [comment]
@tonyganch any news here?

**Comment by aiboy** [comment]
@shuhrat @ascariandrea Can you update to 4.1.0? Looks like an issue is solved there.
