### ISSUE TITLE
Error with parentheses

### ISSUE THREAD

**Issue by rustark** [csscomb/csscomb.js#488]
LESS:

```
.xs ({
    background: none;
});
```

ERROR:

> CSScomb error:
> C:\Users...\lib\core.js:412
> 
> throw e;
> ^
> 
> Please check the validity of the block starting from line #12 
> 
> 10| }
> 12*| .xs({
> 13 |  background: red;
> 14 | });
> 
> Gonzales PE version: 3.0.0-10
> CSScomb  Core version 2.0.2
##

**Comment by aiboy** [comment]
Sorry I can't find this syntax of official LESS site. What this parentheses do? Can you point me out to documentation

http://lesscss.org/#

**Comment by jdalton** [comment]
This seems fixed with the latest csscomb release 😄
