### ISSUE TITLE
Add "space-before-comment"

### ISSUE THREAD

**Issue by gusliedke** [csscomb/csscomb.js#499]
Place a blank line before the docblock comment.

before
```
.example {
  margin: 0;
}
/* This is a variant of the .example component. */
.example--item {
  display: inline;
}
```
after
```
.example {
  margin: 0;
}

/* This is a variant of the .example component. */
.example--item {
  display: inline;
}
```

**Comment by Odisseya** [comment]
And option `space-before-inline-comment` will be useful.

**Comment by jdalton** [comment]
Hi All!

I'm closing this because unless a PR is created it won't likely be addressed.
If you feel strongly about this request I encourage you to dig in and submit a PR 😸
