### ISSUE TITLE
lint-staged

### ISSUE THREAD

**Issue by hadrienl** [csscomb/csscomb.js#512]
Hi,

I'm trying to make csscomb work with lint-staged but it doesn't because csscomb is called by execa with child_process and wait for a stdin instead of calling `processFiles`.

(See : https://github.com/okonet/lint-staged/issues/146#issuecomment-293491771)

**Comment by aiboy** [comment]
@hadrienl closing because since 4.1.0 we have 

   '    -t, --tty-mode',
    '        Run the tool in TTY mode using external app (e.g. IDE).',

**Comment by youtiao66** [comment]
After read source code in 2021-10, I solve my `lint-staged + csscomb` loading error and know what is `--tty-mode`. And then I find this issue. oh no!!! but it doesn't matter, Now I know why and I can memorize it very much. same problem and bug in `git bash`
