### ISSUE TITLE
Parsing error: Please check validity of the block starting from line #1

### ISSUE THREAD

**Issue by herrdu** [csscomb/csscomb.js#514]
When I edit a scss file in VSCode  , i meet this problem , I can't find a way to solve it. Can you  help me ?

### Scss content：
html {
    font-family: 'PingFang SC Microsoft YaHei';
    ;
    font-size: 100px;
    width: 100%;
    height: 100%;
}

### Error Message：
 [CSSComb]

Parsing error: Please check validity of the block starting from line #1
CSScomb Core version: 4.0.0-alpha

1*| html
2 | {
3 |     font-family: 'PingFang SC Microsoft YaHei';;

Syntax: sass
Gonzales PE version: 3.4.7

**Comment by aiboy** [comment]
@herrdu You are trying to use SCSS syntax for SASS file.
