### ISSUE TITLE
Use in JavaScript with React's StyleSheet.create()

### ISSUE THREAD

**Issue by davidpaulsson** [csscomb/csscomb.js#515]
Would it be possible to extend CSSComb to work on this?
```
const styles = StyleSheet.create({
  wrapper: {
    alignItems: 'center',
    backgroundColor: '#f6f6f6',
    borderRadius: 6,
    flex: 1,
    flexDirection: 'row',
    marginBottom: 16,
    marginHorizontal: 16,
    marginTop: 8,
    padding: 12,
  }
});
```
It's probably better suited as a plugin, but just as a thought experiment. Doable?

**Comment by aiboy** [comment]
@davidpaulsson it's doable, we will look into this, but I would not expect it to land soon.

**Comment by davidpaulsson** [comment]
Ok! Thanks for looking into it though 👍 and thanks for a great dev util!

**Comment by valmassoi** [comment]
Or for [styled-components](https://www.styled-components.com/)

**Comment by phoydar** [comment]
Yes. Support for styled components is a must.

**Comment by ApacheEx** [comment]
+1 to have styled-components support:

![image](https://user-images.githubusercontent.com/1918108/37310785-c21f2104-264d-11e8-9233-9ae6b4eed80b.png)

**Comment by dallanlee** [comment]
I landed here in search for CSScomb support within React styled-components. So +1 from me as well

**Comment by danhodkinson** [comment]
+1 from me as well!

**Comment by A11oW** [comment]
Must have!

**Comment by jdalton** [comment]
Hi All!

I'm closing this because unless a PR is created it won't likely be addressed.
If you feel strongly about this request I encourage you to dig in and submit a PR 😸
