### ISSUE TITLE
Auto fix feature

### ISSUE THREAD

**Issue by CKGrafico** [csscomb/csscomb.js#521]
Any chances to have an autofix feature like eslint or tslint?

**Comment by aiboy** [comment]
@CKGrafico autofix - enabled by default

try running ` csscomb filetofix.css ` you will see that file will be fixed

PS: or you want to have support for IDE?

**Comment by CKGrafico** [comment]
But is not using the custom csslint that you have on your project, is it?

**Comment by aiboy** [comment]
@CKGrafico 

Plz read 
https://github.com/csscomb/csscomb.js/blob/dev/doc/configuration.md#create-custom-config

and
https://github.com/csscomb/csscomb.js/blob/dev/doc/configuration.md#where-to-put-config

I thing this is what you want.

**Comment by CKGrafico** [comment]
Yes, I'm using this config but what I'm trying to request as feature is to instead of use this config use de local csslint config file of the project like are doing other plugins ex: tslint, eslint are reading the lint file of the project to fix things
