### ISSUE TITLE
Replace '\n' with os.EOL and add consistency for last new line

### ISSUE THREAD

**Issue by aiboy** [csscomb/csscomb.js#524]
Let's avoid using platform specific constants directly. And new need to output last new line consistently across the app

**Comment by bardware** [comment]
First thing I noticed; inserted line breaks are new line instead of 0D0A

**Comment by aiboy** [comment]
Done partially. We need to detect "line-end" for CSS file and use it instead. Will be done in separate issue

**Comment by bardware** [comment]
> Will be done in separate issue

I just found this issue addressing the new lines: https://github.com/csscomb/csscomb.js/issues/367

**Comment by aiboy** [comment]
@bardware tnx, even more reason to close, since it's duplicate. I fixed output for terminal, but all other places require extra work. Will do that when I got an idea how to handle it. It will be fixed in #367
