### ISSUE TITLE
Option for whitespaces around the comma in “functions”

### ISSUE THREAD

**Issue by kizu** [csscomb/csscomb.js#53]
- `scale(0.5,1)` vs. `scale(0.5, 1)`
- `rgba(0,0,0,.5)` vs. `rgba(0, 0, 0, .5)`

etc.

Maybe, there should be a way to set this option to be different for different functions, for example some people like to set newlines inside gradients etc.
##

**Comment by konius** [comment]
Was this implemented?

**Comment by gajus** [comment]
Who to ping regarding this?

**Comment by jdalton** [comment]
Hi All!

I'm closing this because unless a PR is created it won't likely be addressed.
If you feel strongly about this request I encourage you to dig in and submit a PR 😸
