### ISSUE TITLE
webpack2 with csscomb-loader error

### ISSUE THREAD

**Issue by romanlex** [csscomb/csscomb.js#530]
I have this error:

> ERROR in ./source/styles/app.scss
Module build failed: ModuleBuildError: Module build failed: Error: only one instance of babel-polyfill is allowed

My webpack2 config:
```
{
				test: /\.scss$/,
				use: ExtractTextPlugin.extract({
					fallback: "style-loader",
					use: [{
						loader: "css-loader",
						options: {
							sourceMap: isDebug,
						}
					}, {
						loader: 'csscomb'
					}, {
						loader: 'postcss-loader',
						options: {
							config: './tools/postcss.config.js',
						},
					}, {
						loader: "sass-loader",
						options: {
							sourceMap: isDebug,
						}
					}]
				})
			},
```

**Comment by csantiago132** [comment]
@romanlex im a little lost on how to integrate csscomb with webpack. I had it working with Grunt but have no idea how to use it with webpack. should i

 `npm install csscomb --save-dev`

on webpack
a- `const Comb = require('csscomb');`
b- `const comb = new Comb('zen');`

c- under `... /\ .(css|scss)$/...`

                                           {
						loader: 'csscomb'
					}, {
						loader: 'postcss-loader',
						options: {
							config: './tools/postcss.config.js',
						},
					},


something like this? also, what if you have a .csscomb.json? i think you can `copy/paste` that config and place it like you did under `./tools/postcss.config.js`? please help and thanks!
