### ISSUE TITLE
Turning off the addition of quotes to background URLs

### ISSUE THREAD

**Issue by MichaelTontchev** [csscomb/csscomb.js#538]
Hi,

My company has a preprocessor that requires the background URL to not have any quotes, like

`background: url(resolve/my/path/preprocessor)`

Unfortunately, it doesn't seem that this is configurable in CSScomb. Would it be possible to make this option configurable?

Alternatively, can a rule be turned off for specific lines?

Thanks!
Michael

**Comment by aiboy** [comment]
I don't think we will be able to do conditional rules (at least for now) but I will look into switching it of entirely.

**Comment by jdalton** [comment]
Hi All!

I'm closing this because unless a PR is created it won't likely be addressed.
If you feel strongly about this request I encourage you to dig in and submit a PR 😸
