### ISSUE TITLE
new line between each selector

### ISSUE THREAD

**Issue by harryyuanfeng** [csscomb/csscomb.js#539]
Hi I want to add a new line between each selectors, is there a way to do that?

**Comment by aiboy** [comment]
@harryyuanfeng try this

 "space-after-selector-delimiter": "\n\n",

**Comment by harryyuanfeng** [comment]
`
.result {
                .success {
                    color: @success-modal;
                }
                .btn {
                    &.btn-success {
                        color: @success-modal;
                        border-color: @success-modal;
                    }
                }
            }
`

**Comment by harryyuanfeng** [comment]
before:

.btn {
    &.btn-success {
        color: @success-modal;
        border-color: @success-modal;
    }
}

after:

.btn {
    
    &.btn-success {
        color: @success-modal;
        border-color: @success-modal;
    }
}

**Comment by jdalton** [comment]
Hi @harryyuanfeng!

I'm closing this because unless a PR is created it won't likely be addressed.
If you feel strongly about this request I encourage you to dig in and submit a PR 😸
