### ISSUE TITLE
Option for whitespaces between multiple values

### ISSUE THREAD

**Issue by kizu** [csscomb/csscomb.js#54]
`foo: bar,baz` vs. `foo: bar, baz` or even

``` CSS
foo: bar,
     baz
```

(the latest one should be described using the keyword, I guess)

There could be three (?) similar options for different possible multiple values styles:
1. For comma-separated values: `foo, bar`
2. For space-separated values: `foo bar`
3. For whitespace between the functions and following values: `url()#FFF` vs. `url() #FFF` (this is separate from the previous, 'cause the previous one can't have empty string as an argument).

Also, as with #53, there should be a way to set this option to be different for different properties: for paddings people would want to have `0 0 10px`, but for transforms they would want

``` CSS
transform: scale(1,2)
           rotate(30deg)
```

etc.
##

**Comment by gebidesign** [comment]
Would be a great feature to have!

```sass
// expected result
box-shadow: 0 1px 3px 0 rgba($black, 0.2),
            0 1px 1px 0 rgba($black, 0.14),
            0 2px 1px -1px rgba($black, 0.12);

// actual result
box-shadow: 0 1px 3px 0 rgba($black, 0.2),
0 1px 1px 0 rgba($black, 0.14),
0 2px 1px -1px rgba($black, 0.12);
```

**Comment by JohnONolan** [comment]
Even simpler version of this might be to just "leave code as is" if a newline is detected on a property, eg. I would write @gebidesign's code slightly differently (below). I'd love for it to be sorted, but not change indenting.

```SASS
box-shadow:
    0 1px 3px 0 rgba($black, 0.2),
    0 1px 1px 0 rgba($black, 0.14),
    0 2px 1px -1px rgba($black, 0.12);
```

**Comment by herzinger** [comment]
I came here specifically for finding out it there was some configuration for that already. +1 for sure.

I see it's kind of an old issue, but this or at least some way to ignore a block of code would be huge for me.

**Comment by jdalton** [comment]
Hi All!

I'm closing this because unless a PR is created it won't likely be addressed.
If you feel strongly about this request I encourage you to dig in and submit a PR 😸
