### ISSUE TITLE
Use CssComb on stylus files

### ISSUE THREAD

**Issue by fede-green** [csscomb/csscomb.js#542]
Hello, 

is it possible to use CssComb to reorder properties on .styl files?

thanks!

**Comment by aiboy** [comment]
Hi, yes it is possible. If you will find a bug, feel free to create an issue

**Comment by aiboy** [comment]
@fede-green sorry, I mixed up something in my head. There is no .styl support yet. But it will be in 5.0

https://github.com/csscomb/csscomb.js/issues/159
