### ISSUE TITLE
Npm package do not update the last code？

### ISSUE THREAD

**Issue by zhanfang** [csscomb/csscomb.js#544]
The csscomb package 4.2.0 do not resolve the problem `Only one instance of babel-polyfill is allowed`. 
The package core.js is still as follow:

```
require('babel-polyfill');
```

**Comment by aiboy** [comment]
@zhanfang fix for this problem will be in 4.3.0
https://github.com/csscomb/csscomb.js/pull/531/files

You can track progress here
https://github.com/csscomb/csscomb.js/milestone/18

**Comment by zhanfang** [comment]
@aiboy Thanks！
