### ISSUE TITLE
Option which way of describing colors to use

### ISSUE THREAD

**Issue by kizu** [csscomb/csscomb.js#55]
`#FFF`, `white`, `rgb(255,255,255)` or `hsl(0,0%,100%)`.

This option could take array as an arguments, like `['keyword', 'hexadecimal', 'rgb']`, so you could say that the keywords like `white` are preferred instead of hex, and the hex should be used instead of rgb where possible.
##

**Comment by jdalton** [comment]
Hi All!

I'm closing this because unless a PR is created it won't likely be addressed.
If you feel strongly about this request I encourage you to dig in and submit a PR 😸
