### ISSUE TITLE
Ordering src in @font-face with webpack

### ISSUE THREAD

**Issue by romanlex** [csscomb/csscomb.js#557]
Hello. I found what src in @font-face is ordering after build styles.
After this I cannot load font correctly with webpack.

Example with csscomb:
![image](https://user-images.githubusercontent.com/3369304/32797350-8bca4cdc-c982-11e7-904b-8c6833bf9fea.png)
Without ccscomb - **All work correclty. Font is loaded.**:
![image](https://user-images.githubusercontent.com/3369304/32797378-9fdfb694-c982-11e7-82f6-042d24a10e26.png)

**Comment by csantiago132** [comment]
IMHO, I would exclude this file/directory to avoid this, also, im trying to figure out how to use csscomb with webpack, any leads?

**Comment by csantiago132** [comment]
on your `config` file

      {
           // first line
           "exclude": [
                    "node_modules/**",
                     "path.to/iconFolder/**
            ],
            // more rules
      }

hope this helps!
