### ISSUE TITLE
how  to support .vue file？

### ISSUE THREAD

**Issue by jaxQin** [csscomb/csscomb.js#558]
how  to support .vue file？

**Comment by bbugh** [comment]
FYI, the [vscode-csscomb extension](https://github.com/mrmlnc/vscode-csscomb) works out of the box when paired with the vscode extension for Vue, [Vetur](https://github.com/vuejs/vetur). No special configuration required except to enable csscomb auto formatting: `"csscomb.formatOnSave": true,`

**Comment by mfilar** [comment]
this shouldn't be closed as this repo still lacks support for .vue files. What if I want to format .vue files form the console (on git hooks, CI/CD process)?
