### ISSUE TITLE
integrate csscomb in webpack

### ISSUE THREAD

**Issue by csantiago132** [csscomb/csscomb.js#559]
hi, would like some help 

im a little lost on how to integrate csscomb with webpack. I had it working with Grunt but have no idea how to use it with webpack. should I:

npm install csscomb --save-dev

on webpack
a- const Comb = require('csscomb');
b- const comb = new Comb('zen');

c- under ... /\ .(css|scss)$/...

                                {
					loader: 'csscomb'
				}, {
					loader: 'other loader',
					options: {},
				},
something like this? also, what if you have a .csscomb.json? i think you can copy/paste that config and place it like you did under ./tools/postcss.config.js? please help and thanks!

**Comment by jdalton** [comment]
Hi @csantiago132!

You'll have to create a loader for csscomb. You can see how other loaders are created in [webpack-contrib](https://github.com/webpack-contrib).
