### ISSUE TITLE
Option for margins/paddings/etc. shorthands

### ISSUE THREAD

**Issue by kizu** [csscomb/csscomb.js#56]
`padding: 0 10px` vs. `padding: 0 10px 0 10px`

Some people prefer to always have the longhand ones, while other prefer to have then collapsed.
##

**Comment by jdalton** [comment]
Hi All!

I'm closing this because unless a PR is created it won't likely be addressed.
If you feel strongly about this request I encourage you to dig in and submit a PR 😸
