### ISSUE TITLE
vsCode update to version 1.19 at today, csscomb not work.

### ISSUE THREAD

**Issue by spacecn** [csscomb/csscomb.js#565]
vsCode update to version 1.19 at today, csscomb not work.It was usable before
"csscomb.formatOnSave": true

csscomb.json
{
    "always-semicolon": true,
    "block-indent": 4,
    "color-case": "lower",
    "color-shorthand": true,
    "element-case": "lower",
    "leading-zero": false,
    "quotes": "double",
    "remove-empty-rulesets": false,
    "space-after-colon": "",
    "space-before-colon": "",
    "space-after-combinator": "",
    "space-before-combinator": "",
    "space-before-closing-brace": "\n",
    "space-before-opening-brace": "",
    "space-after-opening-brace": "\n",
    "space-before-selector-delimiter": "",
    "space-after-selector-delimiter": " ",
    "space-between-declarations": 1,
    "strip-spaces": true,
    "unitless-zero": true,
    "vendor-prefix-align": false
}

**Comment by jdalton** [comment]
Hi @spacecn!

Is this still a problem?

**Comment by jdalton** [comment]
Closing as stale. Please ping back if you feel this still needs attention.

**Comment by spacecn** [comment]
Thank you @jdalton 
I'm sorry,I just saw your comment today.The problem has been resolved long ago.

**Comment by jdalton** [comment]
Awesome! Thank you for pinging back @spacecn!
