### ISSUE TITLE
CSSComb 4.2.0 hangs on nth-child whitespace

### ISSUE THREAD

**Issue by gggritso** [csscomb/csscomb.js#569]
Heya! I ran into a _really_ strange CSSComb issue recently. Given the file `test.scss` like this:

```
.e:nth-child( n+1) {
  color: red;
}
```

running `csscomb test.scss` hangs completely. Activity Monitor shows a `node` process eating up 100% memory. A whitespace change to

```
.e:nth-child(n+1) {
  color: red;
}
```

fixes the issue. I've tried clearing my CSSComb settings, but that didn't seem to help.

Is there a really weird crash in CSSComb, or is there something really weird on my computer?

**Comment by jdalton** [comment]
Hi @gggritso!

I can't reproduce on v4.3.0 🎉
