### ISSUE TITLE
Options for order the multiple values when the order don't matter

### ISSUE THREAD

**Issue by kizu** [csscomb/csscomb.js#57]
- `border: 1px solid #FFF` vs. border: `#FFF solid 1px`
- `background: #FFF 0 0 no-repeat url()` vs. `background: url() #FFF no-repeat 0 0 `

 etc.

Of course, when order matters it mustn't be changed (multiple backgrounds, shorthand paddings, `font`, transform etc).

**Comment by tonyganch** [comment]
Closing this issue as a wontfix.
