### ISSUE TITLE
CSScomb error: (node:3168) UnhandledPromiseRejectionWarning: [object Object] (node:3168) 

### ISSUE THREAD

**Issue by rockingaryan** [csscomb/csscomb.js#582]
Every time i try to run CSScomb. :(
![image](https://user-images.githubusercontent.com/34836534/39740703-6d3046a8-52b4-11e8-804f-72450037e0ae.png)

**Comment by cainiaokan** [comment]
same here! any workaround?

**Comment by nrdxp** [comment]
I now am experiencing this error as well, the strange thing is that it was working just yesterday. Platform is Arch Linux installed latest version via yarn.

**Comment by rodfersou** [comment]
same here

**Comment by Jirido** [comment]
I happened to experience the same

**Comment by jdalton** [comment]
Likely fixed by #552 and the v4.3.0 release.
