### ISSUE TITLE
Calc() with multiplication causes "Please check validity"-error

### ISSUE THREAD

**Issue by beckan** [csscomb/csscomb.js#583]
I notice this snippet of CSS:
`
body {
  padding: calc(10 * 10);
}
`
causes following error:
```"Please check validity of the block starting from line #1 CSScomb Core version: 4.2.0".```

I did found out that the root of the problem were inside `gonzales-pe@3.2.7`, so I tried to update `gonzales-pe` to latest version (`4.2.3`). Then the problem was gone.

What do you think, is it time to update `gonzales-pe` or is it causes other issues?

**Comment by jdalton** [comment]
Fixed 🎉
