### ISSUE TITLE
Do not remove property after zero

### ISSUE THREAD

**Issue by muuvmuuv** [csscomb/csscomb.js#586]
I got this code with a grid value:

```
.class {
      grid-template-columns: 1fr 0fr 0;
    }
```

and when I fix the code with csscomb I get this:

```
.class {
      grid-template-columns: 1fr 0 0;
    }
```

csscomb deletes the `fr` from my value, how can I prevent this?

**Comment by GorwinJororis** [comment]
In your `.csscomb.json` set this option:

```
{
    "unitless-zero": false
}
```

**Comment by muuvmuuv** [comment]
Pretty smooth for a workaround but I think it shouldnt remove it no matter false or true

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by GorwinJororis** [comment]
For me, its better to have option instead of default behavior.
