### ISSUE TITLE
How do I use this in VS Code

### ISSUE THREAD

**Issue by wjsiv** [csscomb/csscomb.js#588]
Can you help? I've tried pressing Shift+Alt+F, but it doesn't reformat.  Also, I can'f figure out where to put the .CSScomb.json file to be able to see and edit the options in VS Code.

**Comment by VChet** [comment]
Seems that you have [CSScomb for VS Code](https://github.com/mrmlnc/vscode-csscomb) . To [use it](https://github.com/mrmlnc/vscode-csscomb#usage), press `F1` and run the command named `CSSComb`. [How to set a preset config](https://stackoverflow.com/a/44974447/6633230).

**Comment by tonyganch** [comment]
Thank you for helping, @VChet 🙇

**Comment by vincerubinetti** [comment]
Deprecated :(
